# Generated by Django 4.2.17 on 2025-01-09 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name="task",
            order_with_respect_to="user",
        ),
    ]
